/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _appRouteImport } from './routes/__app'
import { Route as _appHomeIndexRouteImport } from './routes/__app/home/index'
import { Route as _appProfileIndexRouteImport } from './routes/__app/profile/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _appRoute = _appRouteImport.update({
  id: '/__app',
  getParentRoute: () => rootRouteImport,
} as any)
const _appHomeIndexRoute = _appHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => _appRoute,
} as any)
const _appProfileIndexRoute = _appProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => _appRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/': typeof _appHomeIndexRoute
  '/profile/': typeof _appProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof _appHomeIndexRoute
  '/profile': typeof _appProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__app': typeof _appRouteWithChildren
  '/__app/home/': typeof _appHomeIndexRoute
  '/__app/profile/': typeof _appProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home/' | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/profile'
  id: '__root__' | '/' | '/__app' | '/__app/home/' | '/__app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _appRoute: typeof _appRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__app': {
      id: '/__app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__app/home/': {
      id: '/__app/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof _appHomeIndexRouteImport
      parentRoute: typeof _appRoute
    }
    '/__app/profile/': {
      id: '/__app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof _appProfileIndexRouteImport
      parentRoute: typeof _appRoute
    }
  }
}

interface _appRouteChildren {
  _appHomeIndexRoute: typeof _appHomeIndexRoute
  _appProfileIndexRoute: typeof _appProfileIndexRoute
}

const _appRouteChildren: _appRouteChildren = {
  _appHomeIndexRoute: _appHomeIndexRoute,
  _appProfileIndexRoute: _appProfileIndexRoute,
}

const _appRouteWithChildren = _appRoute._addFileChildren(_appRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _appRoute: _appRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
